### ISSUE TITLE
popup problem

### ISSUE THREAD

**Issue by SepidehM** [teofilosalgado/ol-kit#3]
Hi!
I use ol-kit in my project but I have a problem with popup.
I want to show a select box(I mean Select Tag in HTML) in popup, but when I click this select box, popup position changes in map.
how can I solve this problem?

my code is [here ](https://stackblitz.com/edit/react-x53pt1).

**Comment by teofilosalgado** [comment]
Hello!
First of all, thanks for the interactive snippet of code! It was **really** helpful to understand the problem. So, without further ado: what is causing this bug is this line of code [here](https://github.com/teofilosalgado/ol-kit/blob/16dbfa52cc38a7443c3037fe4b99aa747a9c3499/src/Map/Overlay/index.tsx#L19). As you can see, OpenLayers does provide an option to prevent the click event propagation to the DOM tree. Here is a fiddle [here](https://jsfiddle.net/Ld9rup3v/2/) showing how it works. 
It would be nice if we could make `stopEvent` into a prop for the `Overlay` component... Anyway, I am currently at work but feel free to open a PR and it will be promptly accepted 😄 or I may do it myself later on during my lunch break. Whatever comes first.

**Comment by SepidehM** [comment]
thank you for responding!  I create a PR :)
